version: 2.1

orbs:
  win: circleci/windows@4.1.1

jobs:
  build-windows-installer:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Build installer
          command: installer\windows\build_all.cmd
      - store_artifacts:
          path: installer\windows\ParticleCLISetup.exe
          destination: ParticleCLISetup.exe

workflows:
  version: 2
  build:
    jobs:
      - build-windows-installer


